# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spotify.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 640)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1, 0, 1198, 75))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "color: rgb(144, 144, 144);\n"
                                 "font-size: 33px;\n"
                                 "font-family:\n"
                                 "\n"
                                 "")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 95, 531, 381))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pngwing.com.png"))
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(572, 150, 611, 451))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(20, 550, 250, 55))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(-1)
        self.play_button.setFont(font)
        self.play_button.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(224, 224, 224);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "    border-style: solid;\n"
                                       "    border-color: rgb(244, 244, 244);\n"
                                       "    border-width: 3px;\n"
                                       "    border-radius: 22px;\n"
                                       "    font-size: 44px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(227, 227, 227);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:clicked {\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "}")
        self.play_button.setObjectName("play_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(290, 550, 250, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(224, 224, 224);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "    border-style: solid;\n"
                                       "    border-color: rgb(244, 244, 244);\n"
                                       "    border-width: 3px;\n"
                                       "    border-radius: 22px;\n"
                                       "    font-size: 44px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(227, 227, 227);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:clicked {\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "}")
        self.stop_button.setObjectName("stop_button")
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setGeometry(QtCore.QRect(879, 90, 301, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.load_button.setFont(font)
        self.load_button.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(224, 224, 224);\n"
                                       "    color: rgb(0, 0, 0);\n"
                                       "    border-style: solid;\n"
                                       "    border-color: rgb(244, 244, 244);\n"
                                       "    border-width: 3px;\n"
                                       "    border-radius: 22px;\n"
                                       "    font-size: 44px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(227, 227, 227);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:clicked {\n"
                                       "    background-color: rgb(255, 255, 255);\n"
                                       "}")
        self.load_button.setObjectName("load_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPOTIFY"))
        self.label.setText(_translate("MainWindow", "MP3 PLAYER"))
        self.play_button.setText(_translate("MainWindow", "PLAY"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.load_button.setText(_translate("MainWindow", "LOAD"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
